### ISSUE TITLE
Release sample images from blog post

### ISSUE THREAD

**Issue by ghost** [owocki/quotify#1]
I'm wondering where you got the background images from [your blog post](https://owocki.com/quotify-python-library-creating-inspirational-quote-images/) from. And what's the font in the sample images called?

**Comment by owocki** [comment]
@Maplicant here you go => http://bits.owocki.com/042m333h300T/input.zip

**Comment by owocki** [comment]
Fonts => http://bits.owocki.com/34272P1s2J2T/fonts.zip

**Comment by ghost** [comment]
Thanks!

**Comment by owocki** [comment]
One note: I pulled these off of desktop background sites.  Each was presented with a liscense for personal use by the provider I pulled it from, but I can in no way guarantee that that liscense holds in perpetuity or that that's transferable.  Providing above for demo purposes only, it's up to you to do your own diligence before you use them for anything public facing.
